version: '2.3'

services:
  cegapi: # ELEVATOR API
    image: elevator:latest
    ports:
      - 8088:8088
    environment:
        TZ: "Asia/Bangkok"
    volumes:
      - ./compose-resources/api:/var/log/api
